[features]
seeds = false
[programs.localnet]
meta_pass = "5TzpQbN8Mec9c3aiX2KbK5jq6dYUnseDjuzzdjhcFZi4"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/srinivasvalekar/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
